import "./globals.css";
import { Montserrat, Comfortaa, Rubik } from 'next/font/google';

// Initialize the fonts
const montserrat = Montserrat({ 
  subsets: ['latin'],
  variable: '--font-montserrat'
});

const comfortaa = Comfortaa({ 
  subsets: ['latin'],
  variable: '--font-comfortaa'
});

const rubik = Rubik({ 
    subsets: ['latin'],
    variable: '--font-rubik'
});

export const metadata = {
    title: "Metro Garage Solutions",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <body suppressHydrationWarning className={`${montserrat.variable} ${comfortaa.variable} ${rubik.variable}`}>
                {children}
            </body>
        </html>
    );
}